# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommunication.proto\"\x1a\n\x07request\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\x1b\n\x08response\x12\x0f\n\x07message\x18\x01 \x01(\x0c\x32.\n\x06Stream\x12$\n\tMsgStream\x12\x08.request\x1a\t.response\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=23
  _globals['_REQUEST']._serialized_end=49
  _globals['_RESPONSE']._serialized_start=51
  _globals['_RESPONSE']._serialized_end=78
  _globals['_STREAM']._serialized_start=80
  _globals['_STREAM']._serialized_end=126
# @@protoc_insertion_point(module_scope)
